### ISSUE TITLE
Cheetah and Yosemite have same version

### ISSUE THREAD

**Issue by MarkJeronimus** [aurbroszniowski/os-platform-finder#6]
Cheetah is 10.1, Yosemite is 10.10, both are the same **number**. I'm surprised your IDE didn't pick this up.

It's never a good idea to use the inherently inaccurate `double` for comparing exact values. It's the reason everyone always says not to use double values for financial calculations.

The easiest solution I can come up with is replacing the double with a string. The thing you're comparing it to is the osVersion, which is a string anyway. You just need to take the first two numbers. ~~I don't know if the OSX osVersion has more than two parts as I don't use OSX~~ (Apparently it does), and I can't find test cases for it, so I'm checking for it and extracting them. This lead me to the next bug: If the osVersion happens to contain one part (and no dot) your routine crashes. So I also fixed this for Darwin. Furthermore, when the version is not in the map, "null" was silently inserted in the resulting string. It might not be the best solution, but I replaced it by "unknown".

Apparently adding a diff or pull request without a fork is not possible so I'm just posting the patch. And as the patch extension is not allowed I zipped it too.
[OS.java.fix.zip](https://github.com/aurbroszniowski/os-platform-finder/files/5006077/OS.java.fix.zip)

**Comment by aurbroszniowski** [comment]
Hi, 
Thank you for the patch.
The issue with the Double as a key was corrected but I hadn't published the fix yet - it is now done.
Also some other bugs were corrected (incorrect version returned in some cases in a BSD OS), and some refactoring made by some other authors were added.
I added your checks for the "unknown" version in the new version.
Don't hesitate to add further comments if you have some.
Aurelien

**Comment by MarkJeronimus** [comment]
Hi. That was quick (considering your last commit was in 2017)!

**Comment by aurbroszniowski** [comment]
Yes, as most open source developers, I have little time to work on my free projects. Luckily I am on holidays and decided to put some time on your patch, since that you put time to improve this project. This is thanks to people like you that open source projects can make progress so thanks to you. Don't hesitate to contribute again!
